### ISSUE TITLE
normal_score_transform.py error

### ISSUE THREAD

**Issue by joswhite1** [whimian/pyGeoStatistics#2]
Hey, just a note- I've been playing with your library and am quite impressed. I noticed that you get an error in this file at line 121: ' for sc in up_score:' that a float is not iterable. I changed that to 'for sc in upper_scores:' and it seems to run fine, but I haven't taken the time to verify the results. 

I'd be interested in contributing to your code here. I wrote a script to calculate declustering weights with scipy and have been putting together a workflow with data that could be used as an example. 

Send me a message if you're interested.

**Comment by whimian** [comment]
@joswhite1 

Thank you for the bug report.

21ffd3745df31c8961e7d61058468d821df391bf should have corrected it. I don't have the time to write tests for this project for now, so it could be a bit buggy.

It will be great if your algorithm for declustering weights could be integrated into this project.👏

Feel free to fork and submit pull request.
